FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential git

RUN git clone https://github.com/mirrorer/afl
WORKDIR /afl
RUN make && make install

ADD . /repo
WORKDIR /repo
RUN make -f /repo/test/fuzz/Makefile
